### PR TITLE
Update anime-gar.json

### PR DESCRIPTION
**Pull request by JonStark4**
I'm surprised that the likes of KnB and Haikyuu!! have not been added to this achievement, they scream of GAR, the manliness in both these anime is quite overwhelming at times; I've added the first seasons of both these anime, hope you approve my request and add their sequels, prequels, specials and other incarnations. 

Thank you.

### CODE REVIEW

**Comment by tophf** [comment]
I disagree with both KnB and Haikyuu. The two are quite different from the rest of gar titles I've seen (149 so far) in many departments.

**Comment by JonStark4** [comment]
If you could tell me what they lack vis-a-vis other gar titles ?

    On Sunday, 5 June 2016 11:33 PM, tophf <notifications@github.com> wrote:
 

 I disagree with both KnB and Haikyuu. The two are quite different from the rest of gar titles I've seen (149 so far) in many departments.—

**Comment by tophf** [comment]
Well, these two are about boys/bishonens while most of the gar anime have either older men (Golgo) or much more brutal overall setting (Akira, Ippo) or both (Shigurui). BTW Slam Dunk should be removed from the gar list too, I guess.

**Comment by JonStark4** [comment]
I still disagree, I don't think Gar is about older protagonists' (since the likes of Arslan have been added, where the protagonist is not more than 17 and his sidekicks no more than 23-25 or One Punch Man where the protagonists' again araren't more than 21-25) or about brutality (Cowboy Bebop, Space Dandy or Fate Zero are hardly what one would call brutal). 
Honestly, if Giant Killing (also a sports title which centers around football) can get into the gar category, I don't see why KnB and Haikyuu cannot be included in the said category, if anything, the latter two titles are more manly than the former in a more direct and intimidating manner. 
But out of respect for your work, I'll leave it at that, because at the end of the day, I can just giI've suggestions to you and you guys do all the lifting. 
 
  On Tue, 7 Jun, 2016 at 9:09 am, tophf<notifications@github.com> wrote:   
Well, these two are about boys/bishonens while most of the gar anime have either older men (Golgo) or much more brutal overall setting (Akira, Ippo) or both (Shigurui). BTW Slam Dunk should be removed from the gar list too, I guess.

**Comment by tophf** [comment]
Well, as I initially said both KnB and Haikyuu are quite different from other gar anime titles, which I've mostly seen. There's some trait that defines an anime as a whole, otherwise we might put a lot of shonen/spokon entries as well as Death Note just because *occasionally* the characters act cool.

As for Giant Killing, good catch! Should be removed from the list as well.

As for Fate/Zero & Bebop, both mainly feature adult characters (Space Dandy too, iirc). Also Fate/Zero has enough brutal fights with gore, almost like Shigurui.

**Comment by JonStark4** [comment]
I still disagree, but I'll not let this argument go any further because it's going to go no-where, mainly because Gar does not have a specific definition. Since my pull-request is still open, I can only assume that Gineika hasn't seen/is still considering the changes I've made. 
 

    On Tuesday, 7 June 2016 3:34 PM, tophf <notifications@github.com> wrote:
 

 Well, as I initially said both KnB and Haikyuu are quite different from other gar anime titles, which I've mostly seen. There's some trait that defines an anime as a whole, otherwise we might put a lot of shonen/spokon entries as well as Death Note just because occasionally the characters act cool.As for Giant Killing, good catch! Should be removed from the list as well.As for Fate/Zero & Bebop, both mainly feature adult characters (Space Dandy too, iirc). Also Fate/Zero has enough brutal fights with gore, almost like Shigurui.—

**Pull request closed without merging**
